sudo: true
dist: trusty
cache: false
env:
  matrix:
  - URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
  global:
  - secure: K12O0DFCJCtvcFfsMNT4rYVJEWyWkEIEpA1Wx+qhkxpNXMN5qbnSOhoKlHIihBviW7X691FeEUxO3Bm7xNuQaANO56yXXg+w/tKOpAJGEn/UGqMPiLkmkjNVtuYpEr+lnD8ZOkDhPAaPqfToABGfXLeDVj4PT3SNtyA14xKantps+DPmm74PCk04esGUANeZJrWkDPnPced0BiBlR6QTeECgC/eE0hDOFEdJ4uV4oNo0TAmlocKiW9L5YnlX3kYYhgOmRtvgYnlo8owjz1UjaU1Ik6m6UOwlnuhTAwNWpsdlNJm7nzLZKSrYpSla4hohk/z1SQsJ649/fiRaZLa01yM0TclhdGc32Y22FdusBdVF6ElyktpLuD+7vEBcXnVx05CLQIBqg8km6lS4PgJ8c+0ruvkIPEnmsaqJmmVJzxiN1N5F7Hl66pllghsdMHUKYw2NkZ0JKlGFWPoypKaYS+ABmr/pu+06gdaum0nahw0tBMIj9+HDGiH9xG3wRLEJkWumJ1Z4tRER6B/L1DPEZ71FsUREiuDmWN1Md+bNXU8P59yu2lLxJGH3ejsLJg7LP/gX98Dhkk8dYI3txHJh6NGaukDowMPk3CU1z7xbSGQ3i5dbCbsCOnBhNWvPs/H5JXeslZDN+u9Q5ZLyc0RzSmqlDrlNZ9Exog0xKl7t6sA=
  - secure: Otvg+Nq8VpTpYUjj7+R7BwbDi4WhNYluTL9SjL00Gy9MMp2plye7kKv/j1mVE+OGpvRj4UyghHCU7JwcvowoQBl7VzuHwPy06z30j6NDSQ74ThAinGvYVlcsfQ0mCohimoovArVcWLMw1NMRrn060ZyEU97WlB9AmLvWCEtVws4T5ZjtKK0mypQA7MjXoQr4XIUVBKf13XqRLwQfUfV0iazS5QYVI5mv98iqVeftIaPfaUMDVD22/DDURMvCMCZ2rkob7JpgqMdQCaP32q65SGy81ViYAjo7rhdI7nX5f8FpLA9sn6DHKltexpWZdWMYsejLcBIHfTFfeTh9mzDEazaiCkgOQmlFtu3gz2a6hGjeRJAHsBA/ymOTaJhK0OkfyYAolpvQN4ocWIe/StWRJMJzzjFsJqkyxPO+zolQrDkF93T+7ILKcgIQeU4PTCTk72Ck7rLiYjH8ZtSLZHXfdEuxryPxYM8rW7z7Aeii/ZIRXfYJeqYVzJVwYkOwnvDLWNEZv4raXf1VUMMFlCpX1YiDskqjVDzhIYy26faCPirXkgSgoh0tF7mK1vyFRr4Pd0npmLFwP83omJgGig/g0wa/Pca7NMBmMMqUXcXgI3psHsvkF1Yh2/FgB4Txrb4y5VAJ8645LWNu4fQCKMTHETD/16PknAO36vvetTHJ7lA=
before_install:
- openssl version
- openssl aes-256-cbc -k "$key_pwd" -in assets/server.key.enc -out assets/server.key -d
- export SFDX_AUTOUPDATE_DISABLE=true
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- wget -qO- $URL | tar xJf -
- "./sfdx/install"
- export PATH=./sfdx/$(pwd):$PATH
- sfdx update
- sfdx --version
- sfdx plugins --core
- sfdx force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile assets/server.key
  --username $USERNAME --setdefaultdevhubusername -a HubOrg
script:
- sfdx force:org:create -v HubOrg -s -f config/project-scratch-def.json -a ciorg
- sfdx force:source:push -u ciorg
- sfdx force:apex:test:run -u ciorg -c -r human
- sfdx force:org:delete -u ciorg -p
